application: pinboard
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js
  
- url: /pic
  static_dir: pic  

- url: /.*
  script: pinboard.app

libraries:
- name: jinja2
  version: latest  